singleQuote: true
arrowParens: avoid
printWidth: 100
tabWidth: 2
semi: true
trailingComma: es5
htmlWhitespaceSensitivity: strict
plugins: ['prettier-plugin-css-order']
cssDeclarationSorterOrder: alphabetical
overrides:
  - files: '*.html'
    options:
      printWidth: 150