name: Check Formatting of PR Files

# This action works with PRs
on:
  pull_request:
    branches: [main]
    paths:
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.md'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Only fetch the latest commit
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Check code format
        run: |
          npm install --silent prettier
          prettier --check **.{js,md,html,css}
