name: Discord Webhook on Commit

on:
  push:
    branches:
      - '*'

jobs:
  post_to_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Discord message
        id: discord_message
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE=$(cat <<EOF
          {
            "content": "New commit pushed to the repository!",
            "embeds": [
              {
                "title": "Commit Details",
                "description": "A new commit has been pushed.",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}",
                    "inline": true
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}",
                    "inline": true
                  },
                  {
                    "name": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}",
                    "inline": false
                  },
                  {
                    "name": "Commit Author",
                    "value": "${{ github.event.head_commit.author.name }}",
                    "inline": true
                  },
                  {
                    "name": "Commit ID",
                    "value": "${{ github.sha }}",
                    "inline": true
                  }
                ]
              }
            ]
          }
          EOF
          )
          echo "$MESSAGE" > message.json

      - name: Send Discord message
        run: |
          curl -H "Content-Type: application/json" -d "@message.json" -X POST $WEBHOOK_URL
