name: Format Commits

# This action works with pushes
on:
  workflow_dispatch: # Manuall trigger
  pull_request:
    branches: [main]
    paths:
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.md'
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.md'

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Prettify code format
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci --silent
          npx prettier --write *.{js,md,html,css}
          git diff --quiet
          if [ $? == 1 ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add *.{js,md,html,css}
            git commit -m 'Reformatted file'
            git push
            if [ ${{ github.event_name }} == 'pull_request' ]; then
              gh pr comment ${{ github.event.number }} --body 'Reformatted your code. Remember to `git pull` if you plan to continue working on this PR'
            fi
          fi
