name: Format Commits

# This action works with pushes
on:
  workflow_dispatch: # Manuall trigger
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.md'

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # Only fetch the latest commit
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Prettify code format
        run: |
          npm ci
          npx prettier --write *.{js,md,html,css}
          if [ ! $(git status | grep 'nothing added to commit') ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add *.{js,md,html,css}
            git commit -m 'Reformatted file'
            git push
          fi
