name: Format Commits

# This action works with pushes
on:
  workflow_dispatch: # Manuall trigger
  pull_request:
    branches: [main]
    paths:
      - 'scripts/**.js'
      - '**.html'
      - '**.css'
      - '**.md'
  push:
    branches: [main]
    paths:
      - 'scripts/**.js'
      - '**.html'
      - '**.css'
      - '**.md'

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Prettify code format
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci --silent
          npx prettier --write 'scripts/**.js' '**.md' '**.html' '**.css'
          if ! $(git diff --quiet); then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add 'scripts/**.js' '**.md' '**.html' '**.css'
            git commit -m 'Reformatted file'
            git push
            if [ ${{ github.event_name }} == 'pull_request' ]; then
              gh pr comment ${{ github.event.number }} --body 'Reformatted your code. Remember to `git pull` if you plan to continue working on this PR'
            fi
          fi