name: Update Schemas

on:
  workflow_dispatch:

permissions:
  contents: write  # Request write permissions for the workflow

jobs:
  update-schemas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust the Python version as needed

    - name: Install requests library
      run: pip install requests

    - name: Run schema generation script
      run: |
        curl -o 'generate_schemas.py' https://raw.githubusercontent.com/BrutuZ/tachibk-converter/main/tachibk-converter.py
        python generate_schemas.py --dump-schemas

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Schema Assistant'
        git config --global user.email 'schema-assistant@users.noreply.github.com'
        git add schemas/*.proto

        # Check if there are any changes
        if git diff-index --cached --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m 'Update Protobuf schemas'
          git push
        fi
