name: Update Schemas

on:
  workflow_dispatch: {} # Manual Trigger
  schedule:
    - cron: 0 6 * * 1 # Mondays 6AM UTC

permissions:
  contents: write # Request write permissions for the workflow

jobs:
  update-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Generate Schemas
        run: |
          cd site
          uvx --from git+https://github.com/BrutuZ/tachibk-converter tachibk_converter --dump-schemas

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Schema Assistant'
          git config --global user.email 'schema-assistant@users.noreply.github.com'
          git add **/*.proto

          # Check if there are any changes
          if git diff-index --cached --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Update Protobuf schemas'
            git push
          fi
